services:
  php_fpm:
    container_name: nome-do-projeto-php-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - myapp

  nginx:
    container_name: nome-do-projeto-nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - myapp
    depends_on:
      - php_fpm

  mysql:
    container_name: nome-do-projeto-mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "3306:3306"
    networks:
        - myapp
    depends_on:
      - php_fpm

  phpmyadmin:
    container_name: nome-do-projeto-phpmyadmin
    build:
        context: ./docker/phpmyadmin
        dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
    ports:
        - "8081:80"
    networks:
        - myapp
    depends_on:
        - mysql

  redis:
    container_name: nome-do-projeto-redis
    build:
        context: ./docker/redis
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - myapp
    depends_on:
      - php_fpm
      - mysql

networks:
  myapp:
    driver: bridge
